# Generated by Django 6.1 on 2026-08-10 10:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text="Nom d'icône Lucide côté frontend (ex: smartphone).", max_length=64, verbose_name='icône')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='categories.category', verbose_name='catégorie parente')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['parent', 'is_active', 'order'], name='categories__parent__3456f5_idx')],
            },
        ),
    ]
