# Generated by Django 6.1 on 2026-08-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='scope',
            field=models.CharField(choices=[('PRODUCT', 'Produits'), ('SERVICE', 'Services'), ('BOTH', 'Produits et services')], db_index=True, default='BOTH', help_text='PRODUCT, SERVICE ou BOTH — défaut BOTH (compatibilité).', max_length=10, verbose_name='périmètre'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['scope', 'is_active'], name='categories__scope_1ca060_idx'),
        ),
    ]
