# Generated by Django 6.1 on 2026-08-11 16:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('professionals', '0001_professional_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('slug', models.SlugField(max_length=220, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='prix (MAD)')),
                ('price_type', models.CharField(choices=[('FIXED', 'Prix fixe'), ('FROM', 'À partir de'), ('QUOTE', 'Sur devis')], db_index=True, default='FIXED', max_length=10, verbose_name='type de prix')),
                ('duration', models.CharField(blank=True, help_text='Ex: 30 min, 1 h, demi-journée', max_length=80, verbose_name='durée')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('ARCHIVED', 'Archivé')], db_index=True, default='DRAFT', max_length=20, verbose_name='statut')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='mis en avant')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='categories.category', verbose_name='catégorie')),
                ('professional_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='professionals.professionalprofile', verbose_name='profil professionnel')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.URLField(max_length=500, verbose_name='image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='texte alternatif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pro_services.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'image de service',
                'verbose_name_plural': 'images de service',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status', '-created_at'], name='pro_service_status_06cde2_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status', 'price_type'], name='pro_service_status_55ac35_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('professional_profile', 'slug'), name='uniq_service_profile_slug'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gt', 0), _connector='OR'), name='service_price_positive_or_null'),
        ),
        migrations.AddConstraint(
            model_name='serviceimage',
            constraint=models.UniqueConstraint(fields=('service', 'order'), name='uniq_service_image_order'),
        ),
    ]
