# Generated by Django 6.1 on 2026-08-11 18:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_services', '0001_service_and_image'),
        ('professionals', '0002_geolocation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Refusée'), ('CANCELLED', 'Annulée'), ('COMPLETED', 'Terminée')], db_index=True, default='PENDING', max_length=20, verbose_name='statut')),
                ('message', models.TextField(verbose_name='message')),
                ('requested_date', models.DateField(blank=True, null=True, verbose_name='date souhaitée')),
                ('requested_time', models.TimeField(blank=True, null=True, verbose_name='heure souhaitée')),
                ('address', models.CharField(max_length=255, verbose_name='adresse')),
                ('phone', models.CharField(max_length=30, verbose_name='téléphone')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='professionals.professionalprofile', verbose_name='professionnel')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='pro_services.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'demande de service',
                'verbose_name_plural': 'demandes de service',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='pro_service_status_74fe99_idx'), models.Index(fields=['client', '-created_at'], name='pro_service_client__c1cf9a_idx'), models.Index(fields=['professional', '-created_at'], name='pro_service_profess_c26f78_idx')],
            },
        ),
    ]
