# Generated by Django 6.1 on 2026-08-10 09:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('first_name', models.CharField(max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('SELLER', 'Vendeur'), ('ADMIN', 'Administrateur')], db_index=True, default='CLIENT', max_length=10, verbose_name='rôle')),
                ('avatar', models.URLField(blank=True, verbose_name='avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='accès admin Django')),
                ('is_verified', models.BooleanField(default=False, verbose_name='e-mail vérifié')),
                ('email_verified_at', models.DateTimeField(blank=True, help_text="Date de vérification de l'e-mail (Phase 2+).", null=True, verbose_name='e-mail vérifié le')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role', 'is_active'], name='users_user_role_e1ec1a_idx')],
            },
        ),
    ]
