# Generated by Django 6.1 on 2026-08-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('SELLER', 'Professionnel'), ('ADMIN', 'Administrateur')], db_index=True, default='CLIENT', max_length=10, verbose_name='rôle'),
        ),
    ]
