# Generated by Django 6.1 on 2026-08-14 22:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('MESSAGE', 'Message'), ('RECOMMENDATION', 'Recommandation')], db_index=True, default='MESSAGE', max_length=20, verbose_name='type')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('body', models.TextField(max_length=3000, verbose_name='message')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='lu')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'message / recommandation',
                'verbose_name_plural': 'messages & recommandations',
                'ordering': ['-created_at'],
            },
        ),
    ]
