# Generated by Django 6.1 on 2026-08-16 20:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_delivery_fields'),
        ('pro_services', '0002_service_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('NOT_RECEIVED', 'Non reçu / non livré'), ('NOT_AS_DESCRIBED', 'Non conforme à la description'), ('NOT_PERFORMED', 'Prestation non réalisée'), ('PAYMENT_ISSUE', 'Problème de paiement'), ('OTHER', 'Autre')], default='OTHER', max_length=40, verbose_name='motif')),
                ('description', models.TextField(max_length=3000, verbose_name='description')),
                ('seller_reply', models.TextField(blank=True, max_length=3000, verbose_name='réponse vendeur')),
                ('admin_note', models.TextField(blank=True, max_length=3000, verbose_name='note admin')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('SELLER_REPLIED', 'Réponse vendeur'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé'), ('REJECTED', 'Rejeté')], db_index=True, default='OPEN', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_opened', to=settings.AUTH_USER_MODEL, verbose_name='ouvert par')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='orders.order', verbose_name='commande')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='pro_services.servicerequest', verbose_name='demande de service')),
            ],
            options={
                'verbose_name': 'litige',
                'verbose_name_plural': 'litiges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='disputes_di_status_e85bdd_idx'), models.Index(fields=['opened_by', '-created_at'], name='disputes_di_opened__f908fc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('service_request__isnull', True)), models.Q(('order__isnull', True), ('service_request__isnull', False)), _connector='OR'), name='dispute_order_xor_service_request'), models.UniqueConstraint(condition=models.Q(('order__isnull', False), ('status__in', ['OPEN', 'SELLER_REPLIED'])), fields=('order',), name='uniq_open_dispute_per_order'), models.UniqueConstraint(condition=models.Q(('service_request__isnull', False), ('status__in', ['OPEN', 'SELLER_REPLIED'])), fields=('service_request',), name='uniq_open_dispute_per_service_request')],
            },
        ),
    ]
