# Generated by Django 6.1 on 2026-08-11 20:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('duration_days', models.PositiveIntegerField(verbose_name='durée (jours)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='prix (DH)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'forfait boost',
                'verbose_name_plural': 'forfaits boost',
                'ordering': ['duration_days'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('STORE_FREE', 'Boutique Free'), ('STORE_STANDARD', 'Boutique Standard'), ('STORE_PRO', 'Boutique Pro'), ('SERVICE_STANDARD', 'Services Standard'), ('SERVICE_PRO', 'Services Pro')], max_length=40, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('plan_type', models.CharField(choices=[('STORE_FREE', 'Boutique Free'), ('STORE_STANDARD', 'Boutique Standard'), ('STORE_PRO', 'Boutique Pro'), ('SERVICE_STANDARD', 'Services Standard'), ('SERVICE_PRO', 'Services Pro')], db_index=True, max_length=40, verbose_name='type')),
                ('category', models.CharField(choices=[('STORE', 'Boutique'), ('SERVICE', 'Services')], db_index=True, max_length=20, verbose_name='catégorie')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='prix (DH)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='durée (jours)')),
                ('product_limit', models.PositiveIntegerField(blank=True, help_text='Null = illimité. Ignoré pour les plans SERVICE.', null=True, verbose_name='limite produits actifs')),
                ('service_enabled', models.BooleanField(default=False, verbose_name='autorise les services')),
                ('advanced_stats', models.BooleanField(default=False, verbose_name='stats avancées')),
                ('visibility_level', models.PositiveSmallIntegerField(default=0, help_text="0=base, 1=amélioré, 2=pro — n'équivaut pas à une note.", verbose_name='niveau de visibilité')),
                ('boosts_allowed', models.BooleanField(default=False, verbose_name='boosts autorisés')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PlatformPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('account_name', models.CharField(max_length=150, verbose_name='bénéficiaire')),
                ('account_number', models.CharField(blank=True, max_length=120, verbose_name='numéro / compte')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'moyen de paiement SERVIS',
                'verbose_name_plural': 'moyens de paiement SERVIS',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BoostPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROOF_SUBMITTED', 'Preuve envoyée'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Refusé')], db_index=True, default='PENDING', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('proof', models.CharField(blank=True, max_length=500)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_payments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_boost_payments', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boost_payments', to='billing.platformpaymentmethod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('STORE', 'Boutique'), ('SERVICE', 'Services')], db_index=True, max_length=20, verbose_name='catégorie')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré'), ('REJECTED', 'Refusé'), ('CANCELLED', 'Annulé')], db_index=True, default='PENDING', max_length=20, verbose_name='statut')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='début')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expiration')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='activé le')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulé le')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='professionnel')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROOF_SUBMITTED', 'Preuve envoyée'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Refusé')], db_index=True, default='PENDING', max_length=20, verbose_name='statut')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='référence')),
                ('proof', models.CharField(blank=True, max_length=500, verbose_name='preuve (clé storage)')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='preuve envoyée le')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revu le')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='motif de refus')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL, verbose_name='professionnel')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_payments', to='billing.platformpaymentmethod', verbose_name='moyen de paiement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_subscription_payments', to=settings.AUTH_USER_MODEL, verbose_name='revu par')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscription', verbose_name='abonnement')),
            ],
            options={
                'verbose_name': "paiement d'abonnement",
                'verbose_name_plural': "paiements d'abonnement",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('STORE', 'Boutique'), ('PRODUCT', 'Produit'), ('SERVICE', 'Service')], max_length=20)),
                ('target_id', models.UUIDField(verbose_name='cible')),
                ('duration_days', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré'), ('REJECTED', 'Refusé'), ('CANCELLED', 'Annulé')], db_index=True, default='PENDING', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to=settings.AUTH_USER_MODEL, verbose_name='professionnel')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boosts', to='billing.boostpackage')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boost', to='billing.boostpayment')),
            ],
            options={
                'verbose_name': 'boost',
                'verbose_name_plural': 'boosts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id', 'status'], name='billing_boo_target__c0699b_idx'), models.Index(fields=['status', 'expires_at'], name='billing_boo_status_4d1916_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['owner', 'category', 'status'], name='billing_sub_owner_i_51adb8_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'expires_at'], name='billing_sub_status_d93e7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('owner', 'category'), name='uniq_active_subscription_per_owner_category'),
        ),
    ]
