# Generated by Django 6.1 on 2026-08-14 22:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pro_services', '0002_service_request'),
        ('professionals', '0003_professional_social_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('is_visible', models.BooleanField(db_index=True, default=True, help_text='Masqué par la moderation si False.', verbose_name='visible')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_authored', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='professionals.professionalprofile', verbose_name='professionnel')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='pro_services.servicerequest', verbose_name='demande de service')),
            ],
            options={
                'verbose_name': 'avis',
                'verbose_name_plural': 'avis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['professional', '-created_at'], name='reviews_rev_profess_0a6ed2_idx'), models.Index(fields=['author', '-created_at'], name='reviews_rev_author__8385c0_idx'), models.Index(fields=['is_visible', '-created_at'], name='reviews_rev_is_visi_d4dedd_idx')],
            },
        ),
    ]
