# Generated by Django 6.1 on 2026-08-16 19:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_fields'),
        ('products', '0003_product_video_url'),
        ('reviews', '0001_review_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name_snapshot', models.CharField(max_length=200, verbose_name='nom produit (snapshot)')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('is_visible', models.BooleanField(db_index=True, default=True, help_text='Masqué par la moderation si False.', verbose_name='visible')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews_authored', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product_review', to='orders.orderitem', verbose_name='ligne commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'avis produit',
                'verbose_name_plural': 'avis produits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='reviews_pro_product_c1cd86_idx'), models.Index(fields=['author', '-created_at'], name='reviews_pro_author__2f6e8a_idx'), models.Index(fields=['is_visible', '-created_at'], name='reviews_pro_is_visi_2eb5ce_idx')],
            },
        ),
    ]
