# Generated by Django 6.1 on 2026-08-10 13:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('method_type', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Virement bancaire'), ('CASH', 'Espèces'), ('OTHER', 'Autre')], default='MOBILE_MONEY', max_length=30, verbose_name='type')),
                ('account_identifier', models.CharField(blank=True, help_text='Numéro / RIB — configurable en base, jamais en dur dans le code.', max_length=120, verbose_name='identifiant de paiement')),
                ('recipient_name', models.CharField(default='SERVIS', max_length=150, verbose_name='bénéficiaire')),
                ('instructions', models.TextField(help_text='Utilisez {amount} et {currency} pour personnaliser le message.', verbose_name='instructions')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'moyen de paiement',
                'verbose_name_plural': 'moyens de paiement',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant')),
                ('currency', models.CharField(default='MAD', max_length=3, verbose_name='devise')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'En attente de paiement'), ('PENDING_VERIFICATION', 'Preuve en vérification'), ('SUCCESS', 'Payé'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], db_index=True, default='PENDING_PAYMENT', max_length=30, verbose_name='statut')),
                ('transaction_reference', models.CharField(blank=True, max_length=120, verbose_name='référence transaction')),
                ('proof_image', models.CharField(blank=True, max_length=500, verbose_name='preuve (chemin storage)')),
                ('proof_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='preuve envoyée le')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='vérifié le')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='motif de rejet')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order', verbose_name='commande')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='vérifié par')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod', verbose_name='moyen de paiement')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_7a85fd_idx'), models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx')],
            },
        ),
    ]
