# Generated by Django 6.1 on 2026-08-11 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_seller_owned_payments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_status_21ed42_idx',
            old_name='payments_pa_status_9c8e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentmethod',
            new_name='payments_pa_store_i_12b03f_idx',
            old_name='payments_pa_store_i_4a1f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentproof',
            new_name='payments_pa_payment_4d12f2_idx',
            old_name='payments_pa_payment_7b3c1e_idx',
        ),
    ]
