# Generated by Django 6.1 on 2026-08-11 15:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=150, verbose_name='nom affiché')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='slug')),
                ('headline', models.CharField(help_text='Ex: Plombier, Coiffeur, Développeur', max_length=150, verbose_name='métier / titre')),
                ('bio', models.TextField(blank=True, verbose_name='présentation')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('avatar', models.URLField(blank=True, verbose_name='avatar')),
                ('cover', models.URLField(blank=True, verbose_name='bannière')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='longitude')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu')], db_index=True, default='DRAFT', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professional_profiles', to='stores.city', verbose_name='ville')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'profil professionnel',
                'verbose_name_plural': 'profils professionnels',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'city'], name='professiona_status_e7db21_idx'), models.Index(fields=['status', '-created_at'], name='professiona_status_7942e5_idx')],
            },
        ),
    ]
