# Generated by Django 6.1 on 2026-08-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_professional_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='adresse'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=120, verbose_name='quartier'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='code postal'),
        ),
    ]
