# Generated by Django 6.1 on 2026-08-10 10:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('region', models.CharField(max_length=150, verbose_name='région')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'ville',
                'verbose_name_plural': 'villes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='stores_city_is_acti_615e0f_idx')],
            },
        ),
    ]
