# Generated by Django 6.1 on 2026-08-10 11:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('logo', models.URLField(blank=True, verbose_name='logo')),
                ('banner', models.URLField(blank=True, verbose_name='bannière')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspendue')], db_index=True, default='DRAFT', max_length=20, verbose_name='statut')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='stores.city', verbose_name='ville')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'boutique',
                'verbose_name_plural': 'boutiques',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'city'], name='stores_stor_status_39f81d_idx'), models.Index(fields=['status', '-created_at'], name='stores_stor_status_7ba76a_idx')],
            },
        ),
    ]
