# Generated by Django 6.1 on 2026-08-11 17:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='adresse'),
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='store',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=120, verbose_name='quartier'),
        ),
        migrations.AddField(
            model_name='store',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='code postal'),
        ),
    ]
